### ISSUE TITLE
Installation page does not show up

### ISSUE THREAD

**Issue by davehill1900** [wyveo/craftcms-docker#24]
I basically fetched the repo and used `sudo docker-compose up -d` command to run the container. However, when I visit `localhost:80/index.php?p=admin` I get the following error

    Service Unavailable
    Our site is temporarily unavailable. Please try again later.

If I use `localhost:80/admin/install`, I get the following error

    Internal Server Error
    Server Error

So, couldn't make it work at all. Any ideas?

**Comment by colinwilson** [comment]
What do your logs say?

`docker logs -f --tail 10 <WEB CONTAINER NAME/ID>`

**Comment by colinwilson** [comment]
Closed due to lack of response. Re-open if you still require help.

**Comment by JessicaBarnett** [comment]
I had this same issue.  Logs said Redis was failing to start.  This is the error I was getting:
```
➜  craftcms-docker git:(craft3) ✗ docker-compose up
Removing craftcms-docker_redis_1
Starting craftcms-docker_postgres_1 ...
Recreating 5c026aa019eb_craftcms-docker_redis_1 ... error

ERROR: for 5c026aa019eb_craftcms-docker_redis_1  Cannot start service redis: b'Mounts denied: \r\nThe path /data\r\nis not shared from OS X and is not known tStarting craftcms-docker_postgres_1             ... done
 more info.\r\n.'

ERROR: for redis  Cannot start service redis: b'Mounts denied: \r\nThe path /data\r\nis not shared from OS X and is not known to Docker.\r\nYou can configure shared paths from Docker -> Preferences... -> File Sharing.\r\nSee https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.\r\n.'
ERROR: Encountered errors while bringing up the project.
```
I didn't have a '/data' directory at the root of my machine (and added it to docker shared files) as suggested in #1 (which is perhaps the same issue) and #25 , But then redis failed to start because of permissions: 

```
redis_1     | chown: .: Operation not permitted
```

I ended up solving it by going to this code block in docker-compose.yml...
```
    redis:
      image: redis:4.0.11-alpine
      volumes:
        - /data:/data 
```
And changing `/data:/data ` to `./data:/data `

I believe that it was pointing to the root directory before I changed it  (which throws a lot of permission related issues in mac Sierra v10.12.6 ), but I think it should've been pointing to the ./data directory in the craftcms-docker repo.  

Hope that helps someone looking at this in the future.  Thanks!
