### ISSUE TITLE
Craft 2.7: Undefined variable: _SESSION

### ISSUE THREAD

**Issue by egzon-korenica** [wyveo/craftcms-docker#32]
I'm getting an error message each time I decide to go to the admin page of the craft. Homepage shows up normally but going to 172.18.0.4/admin or 172.18.04/index.php?p=admin fails. Everything works normally right at the time the installation is done. After closing the tab and trying to go in again, the error shows up always.

Hope anyone can help on this issue.

**Comment by colinwilson** [comment]
Any further info on your environment? Are you using redis?

**Comment by fmkguy** [comment]
I'm still getting this issue using the latest `craft2` branch.

Steps to reproduce:

1. pull craft2 branch
2. run `docker-compose up`
3. complete the craft cms install steps in the browser at `http://localhost/admin/install`
4. upon "successful" install, try to refresh the page (which redirects me to `http://localhost/admin/login`)

This produces the above `Undefined _SESSON` error and I can't visit any other page after that.

@egzon-korenica It looks like you closed this issue. Would you be able to share how you fixed it or got around it?

**Comment by evan766** [comment]
same issue

**Comment by robertvanstijn** [comment]
Same issue for craft 2 latest branch

**Comment by metakolor** [comment]
Same issue as of today

**Comment by robertvanstijn** [comment]
I got the same error after i tried to run Craft CMS in IIS instead of docker. I found out that the path value in open_basedir in the php.ini file of the php version i used was not the same as the folder my project was in. Adding the path of your project to the open_basedir in docker might solve this problem
![image](https://user-images.githubusercontent.com/6576961/177336580-2389100d-e72c-4bc8-b97d-8c4466f7afeb.png)
